title: "Figure CLI config"
type: object
properties:
  azureDevops:
    type: object
    properties:
      pat:
        type: string
        env: "FIGURE_AZURE_DEVOPS_PAT"
      organisation:
        type: string
        env: "FIGURE_AZURE_ORGANISATION"
      project:
        type: string
        env: "FIGURE_AZURE_PROJECT"
#    required:
#      - pat
#      - organisation
#      - project
#required:
#  - azureDevops
