name: Publish to NPM

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Rush Install
        run: node common/scripts/install-run-rush.js install

      - name: Rush rebuild
        run: node common/scripts/install-run-rush.js rebuild --verbose

      - name: Publish to NPM
        run: node common/scripts/install-run-rush.js publish --apply --publish --target-branch main
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
