name: Publish to NPM

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Git config user
        uses: snow-actions/git-config-user@v1.0.0
        with:
          name: CI Bot
          email: cibot@godfrey.nl

      - name: Authenticate with Token
        run: git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/tristangodfrey/config.git

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14 # or another version if preferred
          registry-url: 'https://registry.npmjs.org'

      - name: Fetch Dependencies
        run: |
          npm ci
          npm install -g @microsoft/rush
          rush update

      - name: Build Projects
        run: rush build

      - name: Publish to NPM
        run: rush publish --apply --publish --target-branch main
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
